name: CI

env:
  TEST_production: ${{ secrets.TEST_production  }}
  TEST_development: ${{ secrets.TEST_development  }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: $AWS_ACCESS_KEY_ID
        aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
        aws-region: $AWS_REGION 

    - name: test the AWS CLI
      run: aws --version && aws ec2 describe-instances
    
      - name: Script... 
      run: |
        echo "the region is $AWS_REGION " 
